#!/bin/bash -i

echo "running demo app"
pwd

if [ "$LUXONIS_DEPTHAI_HOME" = "" ]; then
  echo ':::::::::::::::::::::::::::::::::::::::'
  echo '\nLUXONIS_DEPTHAI_HOME is not set. It must point to the depthai home directory in which the /venv directory is.\n'
  echo ':::::::::::::::::::::::::::::::::::::::'
  exit 1
fi

# check directory exists
if [ -d "$LUXONIS_DEPTHAI_HOME" ]; then
  cd "$LUXONIS_DEPTHAI_HOME" || return 2
else
  echo "LUXONIS_DEPTHAI_HOME points to $LUXONIS_DEPTHAI_HOME which does not exists."
  echo "Point the environmental variable to the correct directory in which Luxonis/depthai repo is."
  exit 3
fi

source venv/bin/activate
echo "running launcher with python verison"
echo python --version
python launcher/launcher.py
